#ifndef CHROMIUM_H_

#define CHROMIUM_H_
#include "build/build_config.h"
#include "base/basictypes.h"
#include "base/port.h"
//#include "base/atomicops.h"
//#include "base/atomicops_internals_x86_msvc.h"
//#include "base/cpu.h"
//#include "base/hash_tables.h"
//#include "base/dynamic_annotations.h"
//#include "base/compiler_specific.h"
//#include "base/scoped_handle.h"
//#include "base/scoped_handle_win.h"
//#include "base/scoped_ptr.h"
//
//#include "base/at_exit.h"
//#include "base/base_paths.h"
//#include "base/base_paths_win.h"
//#include "base/base_switches.h"
//#include "base/command_line.h"
//#include "base/debug_util.h"
//#include "base/file_path.h"
//#include "base/file_util.h"
//#include "base/lock.h"
//#include "base/lock_impl.h"
//#include "base/logging.h"
//#include "base/path_service.h"
//#include "base/platform_thread.h"
//#include "base/process.h"
//#include "base/process_util.h"
//#include "base/registry.h"
//#include "base/singleton.h"
//#include "base/string16.h"
//#include "base/string_piece.h"
//#include "base/string_tokenizer.h"
//#include "base/string_util.h"
//#include "base/string_util_win.h"
//#include "base/sys_string_conversions.h"
//#include "base/win_util.h"


#endif /* end of include guard: CHROMIUM_H_ */
